const nationalityCodes: Record<string, string> = {
  albania: "al",
  algeria: "dz",
  argentina: "ar",
  australia: "au",
  austria: "at",
  belgium: "be",
  bosnia: "ba",
  "bosnia-herzegovina": "ba",
  brazil: "br",
  cameroon: "cm",
  canada: "ca",
  chile: "cl",
  china: "cn",
  colombia: "co",
  croatia: "hr",
  denmark: "dk",
  ecuador: "ec",
  egypt: "eg",
  england: "gb-eng",
  france: "fr",
  germany: "de",
  ghana: "gh",
  greece: "gr",
  hungary: "hu",
  iceland: "is",
  ireland: "ie",
  italy: "it",
  ivorycoast: "ci",
  "ivory coast": "ci",
  japan: "jp",
  mexico: "mx",
  morocco: "ma",
  netherlands: "nl",
  nigeria: "ng",
  "northern ireland": "gb-nir",
  norway: "no",
  paraguay: "py",
  peru: "pe",
  poland: "pl",
  portugal: "pt",
  romania: "ro",
  scotland: "gb-sct",
  senegal: "sn",
  serbia: "rs",
  slovakia: "sk",
  slovenia: "si",
  "south africa": "za",
  "south korea": "kr",
  spain: "es",
  sweden: "se",
  switzerland: "ch",
  turkey: "tr",
  ukraine: "ua",
  uruguay: "uy",
  usa: "us",
  "united states": "us",
  venezuela: "ve",
  wales: "gb-wls",
};

export function getNationalityCode(nationality: string | null): string | null {
  if (!nationality) {
    return null;
  }

  const normalized = nationality.trim().toLowerCase();

  return nationalityCodes[normalized] ?? null;
}
